language: haskell

sudo: false
cache:
  directories:
  - $HOME/.stack/

before_install:
- mkdir -p ~/.local/bin
- export PATH=~/.local/bin:$PATH
- travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.3.0/stack-1.3.0-linux-x86_64.tar.gz | gunzip > ~/.local/bin/stack
- chmod a+x ~/.local/bin/stack

install:
  - stack setup --no-terminal
  - stack build --only-snapshot --no-terminal

script:
  - stack build --no-terminal
